### ISSUE TITLE
CryptoHopper Positions Target

### ISSUE THREAD

**Issue by InfraUltra** [markrickert/cryptohopper-dashboard-watchlist#11]
So, it seems that CH has turned off showing Current Targets for positions that are already open, rendering this feature useless. Wondering if you're able to turn that feature back on so it shows the targets again for positions that are already open.

**Comment by markrickert** [comment]
This feature was added yesterday :D https://github.com/markrickert/cryptohopper-dashboard-watchlist/pull/10
