### ISSUE TITLE
Formatting of target list.

### ISSUE THREAD

**Issue by raga6196** [markrickert/cryptohopper-dashboard-watchlist#18]
Hi, I found an inconsistency in formatting the target list, when there are both green and orange targets.
It seems that:
- The green target is missing a comma;
- There is a trailing comma behind the last target.

![image](https://user-images.githubusercontent.com/20037912/118266061-60730700-b4ba-11eb-97fe-88242604f0ea.png)

**Comment by eatsleepcoderepeat-gl** [comment]
> Hi, I found an inconsistency in formatting the target list, when there are both green and orange targets.
> It seems that:
> 
> * The green target is missing a comma;
> * There is a trailing comma behind the last target.
> 
> ![image](https://user-images.githubusercontent.com/20037912/118266061-60730700-b4ba-11eb-97fe-88242604f0ea.png)

I believe this issue is fixed in pending pull request #17

**Comment by markrickert** [comment]
I just merged #17. @raga6196 Please update the script to the new version and reopen if this didn't fix your issue 👍
